name: bestellbuch
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0" # dart sdk version

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  http: ^0.13.5

  cloud_firestore: ^4.5.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.2

  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  # Add assets from the images directory to the application.
  # - assets/images/
