name: bestellbuch
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0" # dart

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  http: ^0.13.5

  cloud_firestore: ^4.5.2
  firebase_core: ^2.10.0

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  flutter_slidable: ^3.0.0
  numberpicker: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
