// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTql1LIHHKJ3jiX9R_fMlD29WhcY5X1mA',
    appId: '1:156336675241:web:ed9ca589d7517118720cb8',
    messagingSenderId: '156336675241',
    projectId: 'bestellbuch-59c64',
    authDomain: 'bestellbuch-59c64.firebaseapp.com',
    storageBucket: 'bestellbuch-59c64.appspot.com',
    measurementId: 'G-K6M63NFNF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7NyCJs_FrsZpGTvuO9EH1SnhjosvVesU',
    appId: '1:156336675241:android:e5b7065d43d145ee720cb8',
    messagingSenderId: '156336675241',
    projectId: 'bestellbuch-59c64',
    storageBucket: 'bestellbuch-59c64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_3shFjnp_o__eRFxt62bYEAK8lidc9Sc',
    appId: '1:156336675241:ios:81e1a69c1ba51afd720cb8',
    messagingSenderId: '156336675241',
    projectId: 'bestellbuch-59c64',
    storageBucket: 'bestellbuch-59c64.appspot.com',
    iosClientId: '156336675241-vq115q3u2mo2rus222v22r1sgqor0bkv.apps.googleusercontent.com',
    iosBundleId: 'com.shahaab.bestellbuch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_3shFjnp_o__eRFxt62bYEAK8lidc9Sc',
    appId: '1:156336675241:ios:81e1a69c1ba51afd720cb8',
    messagingSenderId: '156336675241',
    projectId: 'bestellbuch-59c64',
    storageBucket: 'bestellbuch-59c64.appspot.com',
    iosClientId: '156336675241-vq115q3u2mo2rus222v22r1sgqor0bkv.apps.googleusercontent.com',
    iosBundleId: 'com.shahaab.bestellbuch',
  );
}
